Apidoc 생성
f-lab-edu/roundLeafCafe pull request #5
Opened 2024-01-24 04:03 UTC by nhs0912

api 문서 생성하였습니다. (멤버 가입 컨트롤러만 작성)

2024-01-25 11:33 UTC, f-lab-justin requested changes

2024-01-25 11:33 UTC, f-lab-justin commented on src/test/java/com/ypdchurch/roundleafcafe/member/controller/MemberControllerTest.java
> +        JSONObject json = new JSONObject();
@nhs0912 
request 객체를 쓰면 어떨까요?

2024-01-27 06:55 UTC, nhs0912 commented on src/test/java/com/ypdchurch/roundleafcafe/member/controller/MemberControllerTest.java
> +        JSONObject json = new JSONObject();
@f-lab-justin  수정하였습니다!

2024-01-27 07:19 UTC, merged

2024-01-29 12:02 UTC, f-lab-justin reviewed
@nhs0912 
수고하셨습니다! 
머징가시지요!